# Generated by Django 5.2.8 on 2025-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_pedido_cidade_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_envio',
        ),
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Em tratamento', 'Em tratamento'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pago', max_length=50),
        ),
    ]
